name: Wetterwarnungen

on:
  schedule:
    - cron: '0 5 * * *'  # Täglich um 05:00 UTC
  workflow_dispatch:

jobs:
  generate_warnungen:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar pytz

      - name: Wetterwarnungen generieren
        run: python generate_warnungen.py

      - name: Zeige docs-Inhalte vor Commit
        run: ls -l docs

      - name: Push aktualisierte ICS-Datei
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          mkdir -p docs
          mv warnungen-dk.ics docs/warnungen-dk.ics
          git add docs/warnungen-dk.ics
          git commit -m "Automatische Aktualisierung der Wetterwarnungen" || echo "Nichts zu committen"
          git push
